# Generated by Django 4.1.7 on 2023-04-04 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Cname", models.CharField(max_length=30)),
                ("Clastname", models.CharField(max_length=30)),
                ("Cphone", models.CharField(max_length=10)),
                ("Cemail", models.EmailField(max_length=254)),
                ("message", models.CharField(max_length=1000)),
                (
                    "userServices",
                    models.CharField(
                        choices=[
                            ("ST", "Fotos de stock"),
                            ("PH", "Servicio de fotografia"),
                            ("AL", "Todos"),
                        ],
                        default="AL",
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="UserData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userName", models.CharField(max_length=30)),
                ("userLastname", models.CharField(max_length=30)),
                ("userPhone", models.CharField(max_length=10)),
                ("userEmail", models.EmailField(max_length=254)),
                ("about", models.CharField(max_length=1000)),
            ],
        ),
    ]
