# Generated by Django 4.1.7 on 2023-03-19 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("lastname", models.CharField(max_length=30)),
                ("phone", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="SBFotografia.user",
                    ),
                ),
                ("message", models.CharField(max_length=1000)),
            ],
            bases=("SBFotografia.user",),
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="SBFotografia.user",
                    ),
                ),
                (
                    "userServices",
                    models.CharField(
                        choices=[
                            ("ST", "Fotos de stock"),
                            ("PH", "Fotografo"),
                            ("BT", "Ambos"),
                        ],
                        default="BT",
                        max_length=2,
                    ),
                ),
            ],
            bases=("SBFotografia.user",),
        ),
    ]
