# Generated by Django 4.1.7 on 2023-03-21 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SBFotografia", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name="userpreference",
            name="userServices",
            field=models.CharField(
                choices=[
                    ("ST", "Fotos de stock"),
                    ("PH", "Fotografo"),
                    ("AL", "Todos"),
                ],
                default="AL",
                max_length=2,
            ),
        ),
    ]
