# Generated by Django 4.1.7 on 2023-04-07 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("SBFotografia", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userName", models.CharField(max_length=30)),
                ("userLastname", models.CharField(max_length=30)),
                ("userPhone", models.CharField(max_length=10)),
                ("userEmail", models.EmailField(max_length=254)),
                ("about", models.CharField(max_length=1000)),
                (
                    "image",
                    models.ImageField(default="default.jpg", upload_to="profilePics"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="UserData",),
    ]
