# Generated by Django 4.1.7 on 2023-04-23 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("SBFotografia", "0002_profile_delete_userdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80)),
                ("category", models.CharField(max_length=40)),
                ("description", models.TextField(blank=True)),
                ("creationDate", models.DateTimeField(auto_now_add=True)),
                ("image", models.ImageField(upload_to="stockPhotos")),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="StockCategory",),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True, default="default.jpeg", null=True, upload_to="profilePics"
            ),
        ),
    ]
